const Student = require('../models/Student');
const Parent = require('../models/Parent');
const User = require('../models/User');
const Class = require('../models/Class');
const School = require('../models/School');
const { sendEmail, invitationEmail } = require('../utils/email');
const { sendSMS } = require('../utils/sms');
const { generateAdmissionLetter, generatePromotionCard, generateTransferCertificate } = require('../utils/pdf');
const FeeCollection = require('../models/FeeCollection');
const { assertWithinLimit } = require('../utils/planLimits');
const escapeRegex = require('../utils/escapeRegex');
const { v4: uuidv4 } = require('uuid');

// Roll-number prefix from a class: "<class number padded to 2><section>",
// e.g. { name: 'Class 9', section: 'A' } → "09A". Non-numeric class names fall
// back to the cleaned uppercased name (e.g. "LKG" → "LKGA").
function classRollPrefix(cls) {
  const name = (cls?.name || '').trim();
  const m = name.match(/\d+/);
  const clsCode = m ? String(parseInt(m[0], 10)).padStart(2, '0') : name.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 4);
  const sec = (cls?.section || '').toUpperCase();
  return `${clsCode}${sec}`;
}

// Re-assign roll numbers (e.g. 09A01, 09A02…) to active students in a class in
// alphabetical name order. Students whose roll was set manually keep it (their
// alphabetical slot is still consumed so the auto rolls around them stay aligned).
async function renumberClassRolls(schoolId, classId) {
  if (!classId) return;
  const cls = await Class.findOne({ _id: classId, school: schoolId }).select('name section').lean();
  if (!cls) return;
  const prefix = classRollPrefix(cls);
  const students = await Student.find({ school: schoolId, currentClass: classId, status: 'active' })
    .select('name rollNumber rollNumberManual').lean();
  students.sort((a, b) => (a.name || '').localeCompare(b.name || '', undefined, { sensitivity: 'base', numeric: true }));
  const ops = [];
  students.forEach((s, i) => {
    if (s.rollNumberManual) return;
    const roll = `${prefix}${String(i + 1).padStart(2, '0')}`;
    if (s.rollNumber !== roll) ops.push({ updateOne: { filter: { _id: s._id }, update: { $set: { rollNumber: roll } } } });
  });
  if (ops.length) await Student.bulkWrite(ops);
}

const DEFAULT_ADMISSION_LETTER = `Dear Parent/Guardian,

We are pleased to inform you that {{student_name}} has been successfully admitted to {{school_name}}.

Admission Details:
- Admission Number: {{admission_number}}
- Class: {{class}} - Section {{section}}
- Academic Year: {{academic_year}}
- Date of Admission: {{admission_date}}

Please ensure that all required documents are submitted within 7 days.

We look forward to nurturing your child's growth and development.

Yours sincerely,
Principal
{{school_name}}
Date: {{date}}`;

const createStudent = async (req, res) => {
  try {
    const schoolId = req.user.school;
    const school = await School.findById(schoolId);

    await assertWithinLimit(school, 'students', 1);   // plan usage cap

    // Format: ADM<year><2-digit per-year sequence>, e.g. ADM202601.
    const year = new Date().getFullYear();
    const yearCount = await Student.countDocuments({ school: schoolId, admissionNumber: new RegExp(`^ADM${year}`) });
    const autoAdmission = `ADM${year}${String(yearCount + 1).padStart(2, '0')}`;
    // Auto-generated by default; admin may override via the edit toggle in the form.
    const admissionNumber = (req.body.admissionNumber && String(req.body.admissionNumber).trim()) || autoAdmission;

    // Create/link guardians
    const guardianIds = [];
    const guardiansInput = Array.isArray(req.body.guardians) ? req.body.guardians : [];
    if (guardiansInput.length > 0) {
      for (const g of guardiansInput) {
        let parent = await Parent.findOne({ phone: g.phone, school: schoolId });
        if (!parent) {
          parent = await Parent.create({ ...g, school: schoolId });
        }
        // Parent login accounts are created selectively in Settings → App Logins.
        guardianIds.push(parent._id);
      }
    }

    const classInfo = req.body.currentClass ? await Class.findById(req.body.currentClass) : null;

    // Roll number: auto-assigned alphabetically per class unless the admin
    // explicitly overrode it in the form (rollNumberManual).
    const isManualRoll = req.body.rollNumberManual === true || req.body.rollNumberManual === 'true';
    const { rollNumber: rnBody, rollNumberManual: _rm, admissionNumber: _an, ...rest } = req.body;
    const student = await Student.create({
      ...rest,
      school: schoolId,
      admissionNumber,
      rollNumberManual: isManualRoll,
      ...(isManualRoll && rnBody ? { rollNumber: String(rnBody).trim() } : {}),
      guardians: guardianIds,
      primaryGuardian: guardianIds[0],
      academicYear: school.academicYear?.current
    });
    if (student.currentClass) await renumberClassRolls(schoolId, student.currentClass);

    // Seed classHistory with the admission class/year
    if (classInfo && student.academicYear) {
      student.classHistory = [{
        classId: classInfo._id,
        className: classInfo.name,
        section: classInfo.section,
        academicYear: student.academicYear,
        startedAt: student.admissionDate || new Date(),
      }];
      await student.save();
    }

    // Update parent with student reference
    for (const gId of guardianIds) {
      await Parent.findByIdAndUpdate(gId, { $addToSet: { students: student._id } });
    }

    // Student login accounts are created selectively in Settings → App Logins.

    const populated = await Student.findById(student._id)
      .populate('currentClass', 'name section')
      .populate('guardians', 'name relation phone');

    res.status(201).json({ success: true, student: populated });
  } catch (err) {
    if (err.code === 11000) return res.status(400).json({ success: false, message: 'A student with this admission number already exists.' });
    res.status(err.status || 500).json({ success: false, message: err.message, code: err.code });
  }
};

const getStudents = async (req, res) => {
  try {
    const { classId, status, search, page = 1, limit = 20 } = req.query;
    const query = { school: req.user.school };
    if (classId) query.currentClass = classId;
    // Default: hide transferred students; pass status=transferred to see only them
    if (status) query.status = status;
    else query.status = { $ne: 'transferred' };
    if (search) {
      const s = escapeRegex(search);
      query.$or = [
        { name: new RegExp(s, 'i') },
        { admissionNumber: new RegExp(s, 'i') },
        { rollNumber: new RegExp(s, 'i') }
      ];
    }

    const total = await Student.countDocuments(query);
    const students = await Student.find(query)
      .populate('currentClass', 'name section')
      .populate('guardians', 'name relation phone')
      .populate('transportRoute', 'routeName vehicleType vehicleNumber routeNumber')
      .sort({ admissionNumber: 1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));

    res.json({ success: true, students, total, page: Number(page), pages: Math.ceil(total / limit) });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

const getStudent = async (req, res) => {
  try {
    const student = await Student.findOne({ _id: req.params.id, school: req.user.school })
      .populate('currentClass', 'name section fees')
      .populate('guardians')
      .populate('primaryGuardian')
      .populate('transportRoute', 'routeName vehicleType vehicleNumber routeNumber')
      .populate('classHistory.classId', 'name section');
    if (!student) return res.status(404).json({ success: false, message: 'Student not found' });

    // Backfill classHistory from transferHistory for students admitted before
    // classHistory seeding was added — so the detail view always shows full history.
    const obj = student.toObject();
    if (obj.transferHistory?.length) {
      for (const t of obj.transferHistory) {
        const ay = t.academicYearAtTransfer;
        const cn = t.classAtTransfer;
        const sec = t.sectionAtTransfer;
        if (!ay) continue;
        const alreadyCovered = obj.classHistory.some(h => {
          const hName = h.classId?.name || h.className;
          const hSec  = h.classId?.section || h.section;
          return h.academicYear === ay && hName === cn && hSec === sec;
        });
        if (!alreadyCovered) {
          // Try to find the original class to get its _id for attendance/exam filtering
          const origClass = await Class.findOne({ school: student.school, name: cn, section: sec });
          obj.classHistory.unshift({
            classId: origClass ? { _id: origClass._id, name: origClass.name, section: origClass.section } : null,
            className: cn,
            section: sec,
            academicYear: ay,
            startedAt: student.admissionDate || null,
            _synthetic: true,
          });
        }
      }
    }

    res.json({ success: true, student: obj });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

const updateStudent = async (req, res) => {
  try {
    const schoolId = req.user.school;
    const before = await Student.findOne({ _id: req.params.id, school: schoolId }).select('currentClass');
    const updateData = { ...req.body };
    // Roll number: keep auto (cleared here so renumber re-assigns) unless the
    // admin overrode it in the form (rollNumberManual).
    const isManualRoll = req.body.rollNumberManual === true || req.body.rollNumberManual === 'true';
    updateData.rollNumberManual = isManualRoll;
    if (isManualRoll) { if (req.body.rollNumber != null) updateData.rollNumber = String(req.body.rollNumber).trim(); }
    else { delete updateData.rollNumber; }
    // Never blank out an existing admission number.
    if (!req.body.admissionNumber || !String(req.body.admissionNumber).trim()) delete updateData.admissionNumber;

    // Resolve guardian objects → Parent ObjectIds (same logic as createStudent)
    const guardiansInput = Array.isArray(req.body.guardians) ? req.body.guardians : [];
    const resolvedParents = []; // track Parent docs for credential creation below
    if (guardiansInput.length > 0) {
      const guardianIds = [];
      for (const g of guardiansInput) {
        if (typeof g === 'string' || g?._id) {
          // Already an ObjectId or populated object — keep as-is
          guardianIds.push(g._id || g);
          const parent = await Parent.findById(g._id || g);
          if (parent) resolvedParents.push(parent);
        } else if (g.phone) {
          let parent = await Parent.findOne({ phone: g.phone, school: schoolId });
          if (!parent) {
            parent = await Parent.create({ ...g, school: schoolId });
          } else {
            await Parent.findByIdAndUpdate(parent._id, { name: g.name, relation: g.relation, alternatePhone: g.alternatePhone });
          }
          resolvedParents.push(parent);
          guardianIds.push(parent._id);
        }
      }
      updateData.guardians = guardianIds;
      if (guardianIds.length > 0) updateData.primaryGuardian = guardianIds[0];
    }

    const student = await Student.findOneAndUpdate(
      { _id: req.params.id, school: schoolId }, updateData, { returnDocument: 'after' }
    ).populate('currentClass', 'name section')
      .populate('guardians', 'name relation phone')
      .populate('transportRoute', 'routeName vehicleType vehicleNumber routeNumber');
    if (!student) return res.status(404).json({ success: false, message: 'Not found' });

    // Ensure student has a User account (creates one if missing)
    const existingStuUser = await User.findOne({ studentId: student._id, school: schoolId });
    if (!existingStuUser) {
      const studentEmail = student.email || `${student.admissionNumber.toLowerCase()}@skl.internal`;
      const stuUser = await User.create({
        school: schoolId, name: student.name, email: studentEmail,
        phone: student.phone, password: student.admissionNumber,
        role: 'student', studentId: student._id, admissionNumber: student.admissionNumber,
      });
      await Student.findByIdAndUpdate(student._id, { user: stuUser._id });
    }

    // Ensure each parent has a User account (creates one if missing)
    for (const parent of resolvedParents) {
      if (!parent.phone) continue;
      const existingParentUser = await User.findOne({ parentId: parent._id, school: schoolId });
      if (!existingParentUser) {
        const parentEmail = parent.email || `${parent.phone}@skl.internal`;
        const parentUser = await User.create({
          school: schoolId, name: parent.name, email: parentEmail,
          phone: parent.phone, password: parent.phone,
          role: 'parent', parentId: parent._id,
        });
        await Parent.findByIdAndUpdate(parent._id, { user: parentUser._id });
      }
    }

    // Re-assign alphabetical roll numbers for the affected class(es).
    const affected = new Set();
    const newClass = student.currentClass?._id || student.currentClass;
    if (newClass) affected.add(String(newClass));
    if (before?.currentClass) affected.add(String(before.currentClass));
    for (const cid of affected) await renumberClassRolls(schoolId, cid);

    const fresh = await Student.findById(student._id)
      .populate('currentClass', 'name section')
      .populate('guardians', 'name relation phone')
      .populate('transportRoute', 'routeName vehicleType vehicleNumber routeNumber');
    res.json({ success: true, student: fresh });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

const deleteStudent = async (req, res) => {
  try {
    const student = await Student.findOneAndDelete({ _id: req.params.id, school: req.user.school });
    if (!student) return res.status(404).json({ success: false, message: 'Not found' });
    // Close the gap left in the class roll sequence.
    if (student.currentClass) await renumberClassRolls(req.user.school, student.currentClass);
    // Remove this student from all parent records
    if (student.guardians?.length) {
      await Parent.updateMany({ _id: { $in: student.guardians } }, { $pull: { students: student._id } });
    }
    // Delete associated user account
    if (student.user) {
      await User.findByIdAndDelete(student.user);
    }
    // Cascade-delete the student's own records so nothing is left orphaned.
    const FeeCollection = require('../models/FeeCollection');
    const StudentLeave = require('../models/StudentLeave');
    const HostelAllocation = require('../models/HostelAllocation');
    await Promise.all([
      FeeCollection.deleteMany({ school: req.user.school, student: student._id }),
      StudentLeave.deleteMany({ school: req.user.school, student: student._id }),
      HostelAllocation.deleteMany({ school: req.user.school, student: student._id }),
    ]);
    res.json({ success: true, message: 'Student deleted' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Promote students
const promoteStudents = async (req, res) => {
  try {
    const { studentIds, toClassId, academicYear } = req.body;
    const toClass = await Class.findById(toClassId);
    if (!toClass) return res.status(404).json({ success: false, message: 'Target class not found' });

    const results = [];
    const affectedClasses = new Set([String(toClassId)]);
    for (const studentId of studentIds) {
      const student = await Student.findOne({ _id: studentId, school: req.user.school });
      if (!student) continue;

      student.promotionHistory.push({
        fromClass: student.currentClass,
        toClass: toClassId,
        academicYear: academicYear || toClass.academicYear,
        promotedAt: new Date(),
        promotedBy: req.user._id
      });

      // Seed classHistory retroactively for students admitted before this feature
      if (!student.classHistory?.length && student.currentClass && student.academicYear) {
        const fromClass = await Class.findById(student.currentClass);
        student.classHistory = [{
          classId: student.currentClass,
          className: fromClass?.name || '',
          section: fromClass?.section || '',
          academicYear: student.academicYear
        }];
      }
      // Push the new class/year entry (avoid duplicate if same year already recorded)
      const alreadyHas = student.classHistory.some(
        h => String(h.classId) === String(toClassId) && h.academicYear === academicYear
      );
      if (!alreadyHas) {
        student.classHistory.push({
          classId: toClassId,
          className: toClass.name,
          section: toClass.section,
          academicYear: academicYear,
          startedAt: new Date()
        });
      }

      student.previousClass = student.currentClass;
      if (student.currentClass) affectedClasses.add(String(student.currentClass));
      student.currentClass = toClassId;
      student.academicYear = academicYear;
      await student.save();
      results.push(student._id);
    }

    // Keep both source and destination class roll sequences alphabetical.
    for (const cid of affectedClasses) await renumberClassRolls(req.user.school, cid);

    res.json({ success: true, message: `${results.length} students promoted`, count: results.length });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Admission letter PDF
const getAdmissionLetterPDF = async (req, res) => {
  try {
    const student = await Student.findOne({ _id: req.params.id, school: req.user.school })
      .populate('currentClass', 'name section');
    if (!student) return res.status(404).json({ success: false, message: 'Not found' });
    const school = await School.findById(req.user.school);
    const template = req.body.template || DEFAULT_ADMISSION_LETTER;
    const data = {
      ...student.toObject(),
      className: student.currentClass?.name,
      section: student.currentClass?.section
    };
    const pdf = await generateAdmissionLetter(data, school.toObject(), template);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Admission_${student.admissionNumber}.pdf`);
    res.send(pdf);
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ID Card data
const getIDCardData = async (req, res) => {
  try {
    const { ids } = req.body;
    const students = await Student.find({ _id: { $in: ids }, school: req.user.school })
      .populate('currentClass', 'name section')
      .populate('primaryGuardian', 'name phone');
    const school = await School.findById(req.user.school);
    res.json({ success: true, students, school });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Preview the next admission number and (alphabetical) roll number for the form.
const suggestCodes = async (req, res) => {
  try {
    const schoolId = req.user.school;
    const { classId, name } = req.query;
    const year = new Date().getFullYear();
    const yearCount = await Student.countDocuments({ school: schoolId, admissionNumber: new RegExp(`^ADM${year}`) });
    const admissionNumber = `ADM${year}${String(yearCount + 1).padStart(2, '0')}`;
    let rollNumber = '';
    if (classId) {
      const cls = await Class.findOne({ _id: classId, school: schoolId }).select('name section').lean();
      if (cls) {
        const prefix = classRollPrefix(cls);
        const students = await Student.find({ school: schoolId, currentClass: classId, status: 'active' }).select('name').lean();
        const target = (name || '').trim();
        const names = students.map(s => s.name || '');
        const combined = (target ? [...names, target] : names)
          .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base', numeric: true }));
        const pos = target ? Math.max(1, combined.indexOf(target) + 1) : combined.length + 1;
        rollNumber = `${prefix}${String(pos).padStart(2, '0')}`;
      }
    }
    res.json({ success: true, admissionNumber, rollNumber });
  } catch (err) { res.status(500).json({ success: false, message: err.message }); }
};

const getPromotionCardPDF = async (req, res) => {
  try {
    const student = await Student.findOne({ _id: req.params.id, school: req.user.school })
      .populate('currentClass', 'name section');
    if (!student) return res.status(404).json({ success: false, message: 'Student not found' });
    if (!student.promotionHistory?.length) {
      return res.status(400).json({ success: false, message: 'No promotion history found for this student.' });
    }

    const school = await School.findById(req.user.school);
    const lastPromotion = student.promotionHistory[student.promotionHistory.length - 1];

    // Use classHistory (denormalized) for from/to details
    const sortedHistory = [...(student.classHistory || [])].sort(
      (a, b) => parseInt(b.academicYear) - parseInt(a.academicYear)
    );
    const toEntry   = sortedHistory[0];
    const fromEntry = sortedHistory[1];

    const data = {
      studentName:      student.name,
      admissionNumber:  student.admissionNumber,
      fromClassName:    fromEntry?.className || '—',
      fromSection:      fromEntry?.section   || '',
      fromAcademicYear: fromEntry?.academicYear || '—',
      toClassName:      toEntry?.className   || student.currentClass?.name || '—',
      toSection:        toEntry?.section     || student.currentClass?.section || '',
      toAcademicYear:   toEntry?.academicYear || lastPromotion.academicYear || student.academicYear || '—',
      promotedAt:       lastPromotion.promotedAt,
      isDoublePromotion: (() => {
        const fromLevel = parseInt((fromEntry?.className || '').match(/\d+/)?.[0] || '0');
        const toLevel   = parseInt((toEntry?.className   || '').match(/\d+/)?.[0] || '0');
        return toLevel - fromLevel >= 2;
      })(),
    };

    const pdf = await generatePromotionCard(data, school.toObject());
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=PromotionCard_${student.admissionNumber}.pdf`);
    res.send(pdf);
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Transfer a student — check pending fees first, then mark transferred + generate TC
const transferStudent = async (req, res) => {
  try {
    const { reason, force } = req.body;
    const student = await Student.findOne({ _id: req.params.id, school: req.user.school })
      .populate('currentClass', 'name section');
    if (!student) return res.status(404).json({ success: false, message: 'Student not found' });
    if (student.status === 'transferred') return res.status(400).json({ success: false, message: 'Student is already transferred.' });

    // Check for pending fees
    const allFees = await FeeCollection.find({ school: req.user.school, student: student._id });
    const pendingFees = allFees.filter(f => {
      const paid = f.paidAmount || 0;
      const net = (f.terms || []).reduce((s, t) => s + (t.amount || 0), 0);
      return paid < net;
    });

    if (pendingFees.length > 0 && !force) {
      const feeSummary = pendingFees.map(f => {
        const net = (f.terms || []).reduce((s, t) => s + (t.amount || 0), 0);
        return {
          _id: f._id,
          academicYear: f.academicYear,
          netAmount: net,
          paidAmount: f.paidAmount || 0,
          pendingAmount: net - (f.paidAmount || 0),
          terms: f.terms,
        };
      });
      return res.status(402).json({ success: false, code: 'FEES_PENDING', pendingFees: feeSummary });
    }

    // Generate TC number: TC + 4-digit school-year count
    const school = await School.findById(req.user.school);
    const year = new Date().getFullYear();
    const tcCount = await Student.countDocuments({
      school: req.user.school,
      'transferHistory.0': { $exists: true },
    });
    const tcNumber = `TC${year}${String(tcCount + 1).padStart(4, '0')}`;

    student.transferHistory.push({
      transferredAt: new Date(),
      tcNumber,
      reason: reason || '',
      classAtTransfer: student.currentClass?.name || '',
      sectionAtTransfer: student.currentClass?.section || '',
      academicYearAtTransfer: student.academicYear || '',
    });
    student.status = 'transferred';
    await student.save();
    if (student.currentClass) await renumberClassRolls(req.user.school, student.currentClass._id || student.currentClass);

    // Generate TC PDF inline
    const lastTransfer = student.transferHistory[student.transferHistory.length - 1];
    const pdfData = {
      studentName:           student.name,
      admissionNumber:       student.admissionNumber,
      admissionDate:         student.admissionDate,
      dateOfBirth:           student.dateOfBirth,
      classAtTransfer:       lastTransfer.classAtTransfer,
      sectionAtTransfer:     lastTransfer.sectionAtTransfer,
      academicYearAtTransfer: lastTransfer.academicYearAtTransfer,
      tcNumber:              lastTransfer.tcNumber,
      reason:                lastTransfer.reason,
      transferredAt:         lastTransfer.transferredAt,
    };
    const pdf = await generateTransferCertificate(pdfData, school.toObject());
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=TC_${student.admissionNumber}.pdf`);
    res.send(pdf);
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Download TC PDF for an already-transferred student
const getTransferCertPDF = async (req, res) => {
  try {
    const student = await Student.findOne({ _id: req.params.id, school: req.user.school })
      .populate('currentClass', 'name section');
    if (!student) return res.status(404).json({ success: false, message: 'Student not found' });
    if (!student.transferHistory?.length) return res.status(400).json({ success: false, message: 'No transfer record found.' });

    const school = await School.findById(req.user.school);
    const lastTransfer = student.transferHistory[student.transferHistory.length - 1];
    const pdfData = {
      studentName:           student.name,
      admissionNumber:       student.admissionNumber,
      admissionDate:         student.admissionDate,
      dateOfBirth:           student.dateOfBirth,
      classAtTransfer:       lastTransfer.classAtTransfer,
      sectionAtTransfer:     lastTransfer.sectionAtTransfer,
      academicYearAtTransfer: lastTransfer.academicYearAtTransfer,
      tcNumber:              lastTransfer.tcNumber,
      reason:                lastTransfer.reason,
      transferredAt:         lastTransfer.transferredAt,
    };
    const pdf = await generateTransferCertificate(pdfData, school.toObject());
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=TC_${student.admissionNumber}.pdf`);
    res.send(pdf);
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// Rejoin a transferred student into a new class
const rejoinStudent = async (req, res) => {
  try {
    const { classId, academicYear } = req.body;
    if (!classId || !academicYear) return res.status(400).json({ success: false, message: 'classId and academicYear are required.' });

    const student = await Student.findOne({ _id: req.params.id, school: req.user.school });
    if (!student) return res.status(404).json({ success: false, message: 'Student not found' });
    if (student.status !== 'transferred') return res.status(400).json({ success: false, message: 'Student is not in transferred status.' });

    const newClass = await Class.findById(classId);
    if (!newClass) return res.status(404).json({ success: false, message: 'Class not found' });

    student.status = 'active';
    student.previousClass = student.currentClass;
    student.currentClass = classId;
    student.academicYear = academicYear;

    student.rejoinHistory.push({
      rejoinedAt: new Date(),
      classId,
      className: newClass.name,
      section: newClass.section,
      academicYear,
    });

    // Add to classHistory for the new year
    const alreadyHas = student.classHistory.some(
      h => String(h.classId) === String(classId) && h.academicYear === academicYear
    );
    if (!alreadyHas) {
      student.classHistory.push({ classId, className: newClass.name, section: newClass.section, academicYear, startedAt: new Date() });
    }

    await student.save();
    await renumberClassRolls(req.user.school, classId);

    const fresh = await Student.findById(student._id)
      .populate('currentClass', 'name section')
      .populate('guardians', 'name relation phone');
    res.json({ success: true, student: fresh });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

module.exports = {
  createStudent, getStudents, getStudent, updateStudent, deleteStudent,
  promoteStudents, getAdmissionLetterPDF, getIDCardData, suggestCodes,
  getPromotionCardPDF, transferStudent, getTransferCertPDF, rejoinStudent
};
